#!/bin/bash

# Variables
pname=$(grep -i pretty_name= /etc/os-release \
    | awk '{gsub("PRETTY_NAME=",""); print}')
op_sys=$(uname -o | tr '[:upper:]' '[:lower:]')
kernelver=$(uname -r | tr '[:upper:]' '[:lower:]')
os_str="os"
kernel_str="kernel"
totalRAM="total"
usedRAM="used"
c0="\033[1;m"
c1="\033[1;31m"
c2="\033[1;32m"
c3="\033[1;33m"
c4="\033[1;34m"
c5="\033[1;35m"
c6="\033[1;36m"


# Proc Functions
usedmem=$(grep "^Active:" \
    /proc/meminfo | sed 's/[^0-9]*//g')
usedMB=$(expr $usedmem / 1024)
totalmem=$(grep -i memtotal \
    /proc/meminfo | sed 's/[^0-9]*//g')
totalMB=$(expr $totalmem / 1024)

# Formatted Output
printf "${c1}${pname}$c0\n"
printf "$c4%10s  $(uname -n)\n$c0" $USER
printf "%10s  $c3$op_sys\n$c0" $os_str
printf "%10s  $c2$kernelver\n$c0" $kernel_str 
printf "%10s  $c5$totalMB\n$c0" $totalRAM
printf "%10s  $c6$usedMB\n$c0" $usedRAM
